# Generated by Django 4.2.6 on 2023-11-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tamanho',
            name='pizza',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='Restaurante',
        ),
        migrations.DeleteModel(
            name='Tamanho',
        ),
    ]
